name: CI

on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v1
        with:
          go-version: '1.19.3'
      - name: Add ~/go/bin to PATH
        run: |
          echo "/home/runner/go/bin" >> $GITHUB_PATH
      - name: Validate code generation
        run: |
          set -xo pipefail
          go mod download && go mod tidy && make generate
          git diff --exit-code -- .
      - run: make test
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          args: --timeout 5m
        env:
          GOROOT: ""
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
  publish:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repo
        uses: actions/checkout@master
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        run: |
          docker build -t ghcr.io/argoproj-labs/argocd-extensions:latest .
          docker push ghcr.io/argoproj-labs/argocd-extensions:latest
