name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v1
        with:
          go-version: '1.19.3'
      - run: make test
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
          args: --timeout 5m
        env:
          GOROOT: ""
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
  publish:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repo
        uses: actions/checkout@master
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: |
            ghcr.io/argoproj-labs/argocd-extensions:${{ github.event.inputs.tag }}
          file: ./Dockerfile
